services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      # - "443:443"
      - "80:80"
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure

  wordpress:
    container_name: ${WP_CONTAINER_NAME}
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    secrets:
      - db_password

  mariadb:
    container_name: ${DB_CONTAINER_NAME}
    build: ./requirements/mariadb/
    networks:
      - internal
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=$WORDPRESS_DB_NAME
      - MYSQL_USER=$WORDPRESS_DB_USER
      - MYSQL_PASSWORD=$WORDPRESS_DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    secrets:
      - db_password
      - db_root_password

networks:
  internal:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/www"
      o: "bind"
  mariadb_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/db"
      o: "bind"
