services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: ${NGINX_CONTAINER_NAME}
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    env_file:
      - .env

  wordpress:
    container_name: ${WP_CONTAINER_NAME}
    image: ${WP_CONTAINER_NAME}
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    build:
      context: ./requirements/wordpress/
      dockerfile: wp.Dockerfile
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    env_file:
      - .env

  mariadb:
    container_name: ${DB_CONTAINER_NAME}
    image: ${DB_CONTAINER_NAME}
    build:
      context: ./requirements/mariadb/
      dockerfile: db.Dockerfile
    networks:
      - internal
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env

networks:
  internal:
    driver: bridge

# secrets:
#   db_password:
#     file: ../secrets/db_password.txt
#   db_root_password:
#     file: ../secrets/db_root_password.txt

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/www"
      o: "bind"
  mariadb_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/db"
      o: "bind"
