services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: ${REDIS_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/redis/
      dockerfile: redis.Dockerfile
    networks:
      - internal
    restart: on-failure
    env_file:
      - .env
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: ${NGINX_CONTAINER_NAME}
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: nginx.Dockerfile
    ports:
      - "443:443"
      - "80:80"
      - "8081:8081"
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost" ]
      interval: 2m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  wordpress:
    container_name: ${WP_CONTAINER_NAME}
    image: ${WP_CONTAINER_NAME}
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: wp.Dockerfile
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 2m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  mariadb:
    container_name: ${DB_CONTAINER_NAME}
    image: ${DB_CONTAINER_NAME}
    build:
      context: ./requirements/mariadb/
      dockerfile: db.Dockerfile
    networks:
      - internal
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  ftp:
    container_name: ${FTP_CONTAINER_NAME}
    image: ${FTP_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/ftp/
      dockerfile: ftp.Dockerfile
    networks:
      - internal
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_volume:/home/${FTP_USER}/ftp/files
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    healthcheck:
      test: [ "CMD", "curl", "-f", "ftp://localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  adminer:
    container_name: ${ADMINER_CONTAINER_NAME}
    image: ${ADMINER_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/adminer/
      dockerfile: adminer.Dockerfile
    networks:
      - internal
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  portfolio:
    container_name: ${PORTFOLIO_CONTAINER_NAME}
    image: ${PORTFOLIO_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/portfolio/
      dockerfile: portfolio.Dockerfile
    networks:
      - internal
    ports:
      - "8080:8080"
    restart: on-failure

  nginx-exporter:
    container_name: ${NGINX_EXPORTER_CONTAINER_NAME}
    image: ${NGINX_EXPORTER_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/observers/nginx-exporter/
      dockerfile: nginx-exporter.Dockerfile
    networks:
      - internal
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    restart: on-failure

  node-exporter:
    container_name: ${NODE_EXPORTER_CONTAINER_NAME}
    image: ${NODE_EXPORTER_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/observers/node-exporter/
      dockerfile: node-exporter.Dockerfile
    networks:
      - internal
    ports:
      - "9100:9100"
    restart: on-failure

  prometheus:
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    image: ${PROMETHEUS_CONTAINER_NAME}
    build:
      context: ./requirements/bonus/observers/prometheus/
      dockerfile: prometheus.Dockerfile
    networks:
      - internal
    ports:
      - "9090:9090"
    depends_on:
      - nginx
      - mariadb
      - wordpress
      - redis
      - ftp
      - adminer
      - nginx-exporter
      - node-exporter
    restart: on-failure

  grafana:
    image: grafana/grafana-oss
    container_name: inception-grafana
    networks:
      - internal
    ports:
      - "3000:3000"

networks:
  internal:
    driver: bridge

# secrets:
#   db_password:
#     file: ../secrets/db_password.txt
#   db_root_password:
#     file: ../secrets/db_root_password.txt

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/www"
      o: "bind"
  mariadb_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/db"
      o: "bind"
  redis_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/inception/cache"
      o: "bind"
