services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./nginx/
    ports:
      - "443:443"
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./wordpress/
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    networks:
      - internal
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env

networks:
  internal:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/www"
      o: "bind"
  mariadb_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/db"
      o: "bind"